#### general settings
name: 003_RRDB_ESRGANx4_DIV2K
use_tb_logger: true
model: srgan
distortion: sr
scale: 4
gpu_ids: [0]

#### datasets
datasets:
  train:
    name: DIV2K
    mode: LQGT
    dataroot_GT: C:\\Users\\Heos\\Repositorys\\BasicSR\\data\\lmdb\\compress_rec.lmdb
    dataroot_LQ: C:\\Users\\Heos\\Repositorys\\BasicSR\\data\\lmdb\\compress_rec_HR.lmdb

    use_shuffle: true
    n_workers: 8  # per GPU
    batch_size: 4 #16
    GT_size: 128 #128
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: val_set14_part
    mode: LQGT
    dataroot_GT: C:\\Users\\Heos\\Repositorys\\BasicSR\\data\\HR\\foreman20_40_PNG
    dataroot_LQ: C:\\Users\\Heos\\Repositorys\\BasicSR\\data\\LR\\foreman20_40_PNG_small_rec

#### network structures
network_G:
  which_model_G: RRDBNet
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 23
network_D:
  which_model_D: discriminator_vgg_128
  in_nc: 3
  nf: 64

#### path
path:
  pretrain_model_G: ../pretrained_models/RRDB_PSNR_x4.pth
  strict_load: true
  resume_state: C:\\Users\\Heos\\Repositorys\\BasicSR\\experiments\\003_RRDB_ESRGANx4_DIV2K\\training_state\\120000.state

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4
  weight_decay_G: 0
  beta1_G: 0.9
  beta2_G: 0.99
  lr_D: !!float 1e-4
  weight_decay_D: 0
  beta1_D: 0.9
  beta2_D: 0.99
  lr_scheme: MultiStepLR

  niter: 400000
  warmup_iter: -1  # no warm up
  lr_steps: [50000, 100000, 200000, 300000]
  lr_gamma: 0.5

  pixel_criterion: l1
  pixel_weight: !!float 1e-2
  feature_criterion: l1
  feature_weight: 1
  gan_type: ragan  # gan | ragan
  gan_weight: !!float 5e-3

  D_update_ratio: 1
  D_init_iters: 0

  manual_seed: 10
  val_freq: !!float 1e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
